### ISSUE TITLE
JSON not updated in output view

### ISSUE THREAD

**Issue by sainitishkumar** [ilovejson/ilovejson#59]
**Describe the bug**
In JSON viewer, when I try to add/ delete a field in output using popup buttons, it gets updated in the source box but not in the output.

**To Reproduce**
1. Go to '/viewer'
2. Add some valid JSON in the source
3. Change the output by add or deleting some fields
4. Only the source gets updated

**Expected behavior**
Both source and output should get updated

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 85

**Comment by dr5hn** [comment]
@sainitishkumar Nice find.

**Comment by dr5hn** [comment]
Fixed in #60
