### ISSUE TITLE
[Security Concern] Uploaded JSON files are publicly accesible at https://cdn.ilovejson.com/

### ISSUE THREAD

**Issue by DiegoFleitas** [ilovejson/ilovejson#71]
**Describe the bug**
AFAIK the data at https://cdn.ilovejson.com/ is publicly accesible & the resulting .json has the unix timestamp as it's name, meaning a third party could end up having the JSON you upload to this webpage if he tries out unix timestamps until he finds one that matches an uploaded file

**To Reproduce**
1. Go to [csv to json](https://www.ilovejson.com/csv-to-json)
2. Upload a csv file
3. Click on convert
4. Click on download
5. See the file URL (https://cdn.ilovejson.com/csvtojson/unixtimestamp.json)

**Expected behavior**
Ensure files are stored only temporarily & viewed only by the uploader.
Alternatively put a BIG WARNING that the webpage is going to make the files you upload to it publicly accesible

**Comment by DiegoFleitas** [comment]
Until this issue is deal with I suggest people to use https://jsonformatter.org/csv-to-json
It's not open source but the FAQ states it only saves JSON files you explicitly click save on & warns the uses that saved links are public unless logged in.

**Comment by dr5hn** [comment]
@DiegoFleitas Thanks for the heads up!

Will fix it up soon.

**Comment by dr5hn** [comment]
@DiegoFleitas Security concern has been solved now.

**Comment by DiegoFleitas** [comment]
> @DiegoFleitas Security concern has been solved now.

Hi Darshan, thanks for the update, but the issue has not been solved. 
I've just tried it and the file is still uploaded publicly on your server after the 2 minutes mark. 
It wasn't deleted after 2 minutes as the notice claims.
ex: https://www.ilovejson.com/downloads/csvtojson/1653240635437.json

**Comment by DiegoFleitas** [comment]
> > @DiegoFleitas Security concern has been solved now.
> 
> Hi Darshan, thanks for the update, but the issue has not been solved. I've just tried it and the file is still uploaded publicly on your server after the 2 minutes mark. It wasn't deleted after 2 minutes as the notice claims. ex: https://www.ilovejson.com/downloads/csvtojson/1653240635437.json @dr5hn

Following up since the URL  I posted is not accesible anymore.
The majority of files uploaded seem to still be kept on your server as you can see [with a simple request you get the data the uploaded file contained regardless how much time passes](https://www.postman.com/lunar-module-astronaut-89452690/workspace/public-workspace/request/13993255-61e410f2-c39a-41e8-a9ba-f4453f9c3785). You should know It is not honest to tell a user his data is deleted when it is not - and in some contexts might actually be illegal - I believe you are knowledgeable enough to do the right thing @dr5hn

**Comment by dr5hn** [comment]
@DiegoFleitas Thanks for your concern. I really appreciate you putting your time into finding security flows within the package.

I will update the notice and say "Your files will be publicly available until 2mins"

Regarding the old CDN server, I have deleted that server, That server doesn't exist anymore so the files are gone now.

I've migrated the app from Heroku to VPS and added a cronjob to delete uploaded files. 

Configuration screenshot
<img width="571" alt="Screenshot 2022-05-25 at 12 48 20 PM" src="https://user-images.githubusercontent.com/6929121/170203631-2f915cc5-d3fe-44cc-8ac8-a7b9850de158.png">

I don't know why it didn't delete your files at the 2mins mark.

Can you help me on how do I solve this issue more efficiently?

**Comment by dr5hn** [comment]
@DiegoFleitas Oh Man, My Bad! Thanks!

I've fixed the cron configuration!
<img width="614" alt="Screenshot 2022-05-26 at 5 50 07 PM" src="https://user-images.githubusercontent.com/6929121/170486669-d43c99ef-5a76-4995-9ac9-5bcf18c511fb.png">

Also can you please help me with updating the notice's wordings? What should it say?

**Comment by DiegoFleitas** [comment]
The notice should be correct now we fixed the cron expression.
Good day
